### ISSUE TITLE
比例尺是不是有问题

### ISSUE THREAD

**Issue by xinleicol** [dvgis/cesium-widget#2]
let pixelDistance = geodesic.surfaceDistance
    let maxBarWidth = 100
    let distance = 0
    for (let i = DIS.length - 1; i >= 0; --i) {
      if (DIS[i] / pixelDistance < maxBarWidth) {
        distance = DIS[i]
        break
      }
    }
    //感觉这里写错了，比例尺应该就是pixelDistance，distance不是比例尺吧，下面的循环把比例尺转成整数
    let scaleDistance = 0 //比例尺
    for (let i = 0; i < DIS.length; i++) {
      if (DIS[i] / pixelDistance >= 1) {
        scaleDistance = DIS[i]
        break
      }      
    }
    if (distance && scaleDistance) {
      this._wrapper.style.visibility = 'visible'
      this._labelEl.innerHTML =
        scaleDistance >= 1000 ? `${distance / 1000} km` : `${distance} m`
      let barWidth = (distance / pixelDistance) | 0
      this._scaleBarEl.style.cssText = `width: ${barWidth}px; left: ${(125 -
        barWidth) /
        2}px;`
    }
  }

**Comment by cavencj** [comment]
已修复
